# Generated by Django 5.2 on 2025-05-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0002_remove_job_posted_at_remove_job_title_job_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
