# Generated by Django 5.2 on 2025-04-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_content', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('is_parsed', models.BooleanField(default=False)),
                ('last_parsed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='Candidate.candidate')),
            ],
        ),
    ]
