# Generated by Django 5.2 on 2025-04-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Candidate', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_skills', models.JSONField(default=dict, help_text='Extracted skills from resume')),
                ('parsed_education', models.JSONField(default=dict, help_text='Extracted education details')),
                ('parsed_experience', models.JSONField(default=dict, help_text='Extracted work experience')),
                ('parsed_projects', models.JSONField(default=dict, help_text='Extracted project details')),
                ('skills_score', models.PositiveSmallIntegerField(default=0, help_text='Score for skills match')),
                ('experience_score', models.PositiveSmallIntegerField(default=0, help_text='Score for experience relevance')),
                ('education_score', models.PositiveSmallIntegerField(default=0, help_text='Score for education match')),
                ('overall_score', models.PositiveSmallIntegerField(default=0, help_text='Overall resume score')),
                ('strengths', models.TextField(blank=True, help_text='Resume strengths')),
                ('weaknesses', models.TextField(blank=True, help_text='Areas for improvement')),
                ('improvement_suggestions', models.TextField(blank=True, help_text='Suggestions to improve resume')),
                ('keyword_matches', models.JSONField(default=dict, help_text='Matched keywords from job description')),
                ('keyword_match_percentage', models.FloatField(default=0.0, help_text='Percentage of keywords matched')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='Candidate.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to='Candidate.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('skill', 'Skill'), ('experience', 'Experience'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('weight', models.FloatField(default=1.0, help_text='Importance weight of this keyword')),
                ('found_in_resume', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='AI_Analysis.resumeanalysis')),
            ],
        ),
    ]
